version: "3.5"

services:

  redis:
    container_name: rmap-redis
    image: redis:6.0
    command: redis-server --requirepass REconDIS
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./data-redis:/data

  mysql:
    container_name: rmap-mysql
    image: quay.io/reconmap/rest-api-db:latest
    restart: unless-stopped
    volumes:
      - ./data-mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: reconmuppet
      MYSQL_DATABASE: reconmap
      MYSQL_USER: reconmapper
      MYSQL_PASSWORD: reconmapped

  web-client:
    container_name: rmap-web-client
    image: quay.io/reconmap/web-client:master
    restart: unless-stopped
    volumes:
      - /data/compose/reconmap/environment.js:/usr/share/nginx/html/environment.js:ro
    ports:
      - 5500:5500

  api:
    container_name: rmap-api
    image: quay.io/reconmap/rest-api:latest
    restart: unless-stopped
    volumes:
      - /data/compose/reconmap/config.json:/var/www/webapp/config.json
      - /data/compose/reconmap/logs:/var/www/webapp/logs/
      - /data/compose/reconmap/data:/var/www/webapp/data/
    ports:
      - 5510:5510
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USER: default
      REDIS_PASSWORD: REconDIS

  agent:
    container_name: rmap-agent
    image: quay.io/reconmap/agent:latest
    restart: unless-stopped
    ports:
      - 5520:5520
    environment:
      VALID_ORIGINS: http://localhost:5500
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: REconDIS


